site_name: 【非公式】BedWars (日本語訳Docs)
copyright: "&copy; 2023 Developer:ScreamingSandals Writer:Kinoko_2K"

nav:
  - Home: index.md
  - アリーナの作成: arena.md
  - 構成: config.md
  - コマンドと権限情報: commands.md
  - お店: shop.md
  - アップグレード: upgrades.md
  - PlaceholderAPI情報: placeholderapi.md
  - 特別なアイテム: specials.md
  - トラブルシューティングとよくある質問: troubleshooting.md
  - API情報: api.md
  - その他: others.md
theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - navigation.top
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ScreamingSandals
    - icon: fontawesome/brands/discord
      link: https://screamingsandals.org/discord
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - toc:
      permalink: true
